FROM leafai/studio-go-runner-dev-base:0.0.4

MAINTAINER karlmutch@gmail.com

ENV LANG C.UTF-8

ENV GO_VERSION 1.14.4

RUN \
    apt-get update && apt-get install -y apt-transport-https && \
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list && \
    apt-get update && \
    apt-get install -y kubectl && \
    mkdir -p /usr/local/bin && \
    opsys=linux && \
    (cd /usr/local/bin ; curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash)

RUN \
    cd /var && \
    wget -q -O /tmp/go.tgz https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar xzf /tmp/go.tgz && \
    rm /tmp/go.tgz

ENV GOROOT=/var/go
ENV GOPATH=/project
ENV PATH=$GOROOT/bin:$GOPATH/bin:$PATH:/project/.local/bin

ENV LOGXI='*=INF'
ENV LOGXI_FORMAT='happy,maxcol=1024'

ENV ENCRYPT_DIR='/runner/certs/message'

RUN \
    mkdir -p $GOPATH/bin && \
    (curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh)

RUN \
    git config --global url."https://github.com/".insteadOf git@github.com: && \
    git config --global url."https://".insteadOf git:// && \
    go get github.com/karlmutch/enumer && \
    go get github.com/karlmutch/petname && \
    go install github.com/karlmutch/petname/cmd/petname && \
    wget -q -O $GOPATH/bin/semver https://github.com/karlmutch/duat/releases/download/0.13.0/semver-linux-amd64 && \
    wget -q -O $GOPATH/bin/stencil https://github.com/karlmutch/duat/releases/download/0.13.0/stencil-linux-amd64 && \
    chmod +x $GOPATH/bin/semver && \
    chmod +x $GOPATH/bin/stencil && \
    mkdir -p /runner/certs/message

WORKDIR /project/src/github.com/leaf-ai/studio-go-runner

LABEL author="Karl Mutch"

# The following steps invalidates the cache at this point in the Dockerfile, stencil will substitute a
# # new date time on every run changing the argument
ARG CACHE_END="{{now}}"
RUN CACHE_END=${CACHE_END} ls > /dev/null
COPY . /project/src/github.com/leaf-ai/studio-go-runner/

CMD /bin/bash -c './ci.sh'

# Done last to prevent lots of disruption when bumping versions
LABEL vendor="Open Source"
