FROM registry.container-registry.svc.cluster.local:5000/leafai/studio-go-runner-dev-base:0.0.5

MAINTAINER karlmutch@gmail.com

ENV LANG C.UTF-8

# Protobuf version
ENV PROTOBUF_VERSION="3.13.0"
ENV PROTOBUF_ZIP=protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
ENV PROTOBUF_URL=https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/${PROTOBUF_ZIP}

RUN wget ${PROTOBUF_URL} && \
    unzip ${PROTOBUF_ZIP} -d /usr && \
    chmod +x /usr/bin/protoc && \
    find /usr/include/google -type d -print0 | xargs -0 chmod ugo+rx && \
    chmod -R +r /usr/include/google

ENV GO_VERSION 1.15.2

RUN \
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list && \
    apt-get update && \
    apt-get install -y kubectl && \
    mkdir -p /usr/local/bin && \
    opsys=linux && \
    (cd /usr/local/bin ; curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash)

RUN \
    mkdir -p /project/go && \
    mkdir -p /project/src/github.com/leaf-ai && \
    cd /project && \
    wget -q -O /tmp/go.tgz https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar xzf /tmp/go.tgz && \
    rm /tmp/go.tgz

ENV GOPATH=/project
ENV PATH=$GOPATH/bin:$PATH
ENV PATH=$PATH:/project/.local/bin:/project/go/bin
ENV GOROOT=/project/go

ENV LOGXI='*=INF'
ENV LOGXI_FORMAT='happy,maxcol=1024'

ENV ENCRYPT_DIR='/runner/certs/message'

RUN \
    mkdir $GOPATH/bin && \
    git config --global url."https://github.com/".insteadOf git@github.com: && \
    git config --global url."https://".insteadOf git:// && \
    go get github.com/karlmutch/enumer && \
    go get github.com/karlmutch/petname && \
    go install github.com/karlmutch/petname/cmd/petname && \
    wget -q -O $GOPATH/bin/semver https://github.com/karlmutch/duat/releases/download/0.13.0/semver-linux-amd64 && \
    wget -q -O $GOPATH/bin/stencil https://github.com/karlmutch/duat/releases/download/0.13.0/stencil-linux-amd64 && \
    chmod +x $GOPATH/bin/semver && \
    chmod +x $GOPATH/bin/stencil && \
    mkdir -p /runner/certs/message && \
    rm /usr/bin/nvidia-* && \
    apt-get install -y rsync

LABEL author="Karl Mutch"
LABEL vendor="Open Source"

WORKDIR /project/src/github.com/leaf-ai/studio-go-runner

# In order to invalidate the cache correctly for th next set of layers copy the git HASH to the container
# from the volume mounted into the build step provisioned by Mikasu
#
COPY .git/HEAD /tmp/HEAD

RUN cd /makisu-context && \
    tar cf /project/src/github.com/leaf-ai/studio-go-runner/src.tar . && \
    cat /makisu-context/.git/HEAD

CMD [ "/bin/bash", "-c", "tar xf src.tar && ./ci.sh" ]
