FROM localhost:5000/leafai/studio-go-runner-dev-base:0.0.2

MAINTAINER karlmutch@gmail.com

ENV LANG C.UTF-8

ENV GO_VERSION 1.11.9

RUN \
    apt-get update && apt-get install -y apt-transport-https && \
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list && \
    apt-get update && \
    apt-get install -y kubectl

RUN \
    mkdir -p /project/go && \
    mkdir -p /project/src/github.com/leaf-ai && \
    cd /project && \
    wget -q -O /tmp/go.tgz https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar xzf /tmp/go.tgz && \
    rm /tmp/go.tgz

ENV GOPATH=/project
ENV PATH=$GOPATH/bin:$PATH
ENV PATH=$PATH:/project/.local/bin:/project/go/bin
ENV GOROOT=/project/go

ENV LOGXI='*=INF'
ENV LOGXI_FORMAT='happy,maxcol=1024'

WORKDIR /project/src/github.com/leaf-ai/studio-go-runner

RUN \
    mkdir $GOPATH/bin && \
    (curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh) && \
    git config --global url."https://github.com/".insteadOf git@github.com: && \
    git config --global url."https://".insteadOf git:// && \
    go get github.com/karlmutch/enumer && \
    go get github.com/karlmutch/petname && \
    go install github.com/karlmutch/petname/cmd/petname && \
    wget -q -O $GOPATH/bin/semver https://github.com/karlmutch/duat/releases/download/0.11.1/semver-linux-amd64 && \
    wget -q -O $GOPATH/bin/stencil https://github.com/karlmutch/duat/releases/download/0.11.1/stencil-linux-amd64 && \
    chmod +x $GOPATH/bin/semver && \
    chmod +x $GOPATH/bin/stencil && \
    rm /usr/bin/nvidia-*

LABEL author="Karl Mutch"
LABEL vendor="Open Source"

RUN mkdir -p /project/src/github.com/leaf-ai/studio-go-runner && \
    cp -r /makisu-context/. /project/src/github.com/leaf-ai/studio-go-runner/.

WORKDIR /project/src/github.com/leaf-ai/studio-go-runner

CMD /bin/bash -c './ci.sh'
