= StudioML distributed evaluation and model serving
ifdef::env-github[]
:imagesdir:
https://raw.githubusercontent.com/leaf-ai/studio-go-runner/main/docs/artwork
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:imagesdir: ./
endif::[]

++++
<script src="assets/clipboard.js"></script>
<style>
 .listingblock:hover .clipboard {
     display: block;
 }

 .clipboard {
     display: none;
     border: 0;
     font-size: .75em;
     text-transform: uppercase;
     font-weight: 500;
     padding: 6px;
     color: #999;
     position: absolute;
     top: .425rem;
     right: .5rem;
     background: transparent;
 }

 code + .clipboard {
     top: 2rem !important;
 }

 .clipboard:hover, .clipboard:focus, .clipboard:active {
     outline: 0;
     background-color: #eee9e6;
 }
</style>
<script>
 $(function() {
     var pre = document.getElementsByTagName('pre');
     for (var i = 0; i < pre.length; i++) {
	 var b = document.createElement('button');
	 b.className = 'clipboard';
	 b.textContent = 'Copy';
         if (pre[i].childNodes.length === 1 && pre[i].childNodes[0].nodeType === 3) {
	     var div = document.createElement('div');
	     div.textContent = pre[i].textContent;
             pre[i].textContent = '';
             pre[i].appendChild(div);
         }
	 pre[i].appendChild(b);
     }
     new ClipboardJS('.clipboard', {
	 target: function(b) {
             var p = b.parentNode;
	     return p.className.includes("highlight")
                  ? p.getElementsByClassName("code")[0]
                  : p.childNodes[0];
         }
     }).on('success', function(e) {
	 e.clearSelection();
	 e.trigger.textContent = 'Copied';
	 setTimeout(function() {
	     e.trigger.textContent = 'Copy';
	 }, 2000);
     });
 });
</script>
++++

:toc:
:toc-placement!:

This document details a Google Cloud deployment of a standalone StudioML compute cluster.

toc::[]

== Setup

[source,shell]
----
snap install google-cloud-sdk --classic
gcloud init
----
