= StudioML distributed evaluation and model serving
ifdef::env-github[]
:imagesdir:
https://raw.githubusercontent.com/leaf-ai/studio-go-runner/main/docs/artwork
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:imagesdir: ./
endif::[]

:toc:
:toc-placement!:

This document details a Google Cloud deployment of a standalone StudioML compute cluster.

Thisd document is aimed at an audience with Google Cloud skills and sufficent account rights for full account management.

toc::[]

== Setup

:source-highlighter: coderay

[source,shell]
----
$ snap install google-cloud-sdk --classic
$ gcloud init
Welcome! This command will take you through the configuration of gcloud.

Your current configuration has been set to: [default]

You can skip diagnostics next time by using the following flag:
  gcloud init --skip-diagnostics

Network diagnostic detects and fixes local network connection issues.
Checking network connection...done.
Reachability Check passed.
Network diagnostic passed (1/1 checks passed).

You must log in to continue. Would you like to log in (Y/n)?  y

Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/auth?redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&prompt=select_account&response_type=code&client_id=999999999.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&access_type=offline


Enter verification code: 347dHJG^#234/&T&WSHid237


To take a quick anonymous survey, run:
  $ gcloud alpha survey

You are logged in as: [karl.mutch@cognizant.com].

Pick cloud project to use:
 [1] cdb-aia-leaf1000999999
 [2] Create a new project
Please enter numeric choice or text value (must exactly match list
item):  1

Your current project has been set to: [cdb-aia-leaf1000999999].

Not setting default zone/region (this feature makes it easier to use
[gcloud compute] by setting an appropriate default value for the
--zone and --region flag).
See https://cloud.google.com/compute/docs/gcloud-compute section on how to set
default compute region and zone manually. If you would like [gcloud init] to be
able to do this for you the next time you run it, make sure the
Compute Engine API is enabled for your project on the
https://console.developers.google.com/apis page.

Created a default .boto configuration file at [/home/kmutch/.boto]. See this file and
[https://cloud.google.com/storage/docs/gsutil/commands/config] for more
information about configuring Google Cloud Storage.
Your Google Cloud SDK is configured and ready to use!

* Commands that require authentication will use karl.mutch@cognizant.com by default
* Commands will reference project `cdb-aia-leaf1000999999` by default
Run `gcloud help config` to learn how to change individual settings

This gcloud configuration is called [default]. You can create additional configurations if you work with multiple accounts and/or projects.
Run `gcloud topic configurations` to learn more.

Some things to try next:

* Run `gcloud --help` to see the Cloud Platform services you can interact with. And run `gcloud help COMMAND` to get help on any gcloud command.
* Run `gcloud topic --help` to learn about advanced features of the SDK like arg files and output formatting
----

For more information please see, https://cloud.google.com/sdk/docs/downloads-snap.

== RabbitMQ on Google Cloud

The RabbitMQ component of a runner deployment is typically a stable component that can be deployed using a Virtual Machine outside of a Kubernetes cluster.  The easiest way to deploy this component is via the Google Marketplace distribution of the bitnami packaged RabbitMQ non clustered version and the Google click to deploy option.

When creating the VM a base configuration should start with the n1-standard-2 configuration, and a 20GB Standard Disk.

Choose a zone for the VM that fits your requirements for other compute resource availability, for example a zone that can host your GPU based instances for StudioML.

For more information please review the https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/rabbitmq/README.md#installation[Bitnami RabbitMQ Installation README].

After deployment the Cloud Console Deployment Manager can be used to access your deployment and will show a temporary admin password and IP address for the machine.  The deployment page can be used to create an SSH session to the machine, once logged in the default admin password can be changed using the following command:

[source, shell]
----
sudo rabbitmqctl change_password admin NEW_PASSWORD
----
 
The SSH shell can also be used to add user accounts for the experimenters wishing to queue work to your compute cluster.  Bitnami packaging for services is similar across cloud providers so the commands should be the same across providers for SSH based administration, for more information about adding users etc please see, https://docs.bitnami.com/bch/infrastructure/rabbitmq/administration/[Bitnami RabbitMQ Administration].

If you intend on accessing the RabbitMQ server externally then you will need to assign an external IP address for the machine using the instructions posted at, https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address?hl=en_US#promote_ephemeral_ip[Promoting an ephemeral external IP address].

In addition the firewall for the VM network interface should be configured to allow for ports 5672, and 15672 to be permitted for inbound connections.

Having configured RabbitMQ you should updated any StudioML configuration file being used with the new external IP address, username, and password as follows:

[source,yaml]
----
cloud:
    queue: 
        rmq: "amqp://[username]:[password]@[external IP address]:5672/%2f?connection_attempts=30&retry_delay=.5&socket_timeout=5"

server:
    authentication: None

----

In the event that you remain with a Google account level IP address this should be used for the configuration.

===Google Cloud Storage

=== Studio Go Runner


