= SQS queue status query tool
Copyright 2021 (c) Cognizant Digital Business, Evolutionary AI. All rights reserved. Issued under the Apache 2.0 license.
ifdef::env-github[]
:imagesdir:
https://raw.githubusercontent.com/cognizantcodehub/LEAF-ManyMinima/main/docs/artwork
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

ifndef::env-github[]
:imagesdir: ./
endif::[]

:source-highlighter: pygments
:source-language: go


This tool is motivated by a need to have a way of discovering outstanding work in SQS queues and provision using Kubernetes any compute needs that these queues have.

:toc:

== Usage

To print a JSON formatted list of queues on AWS simply run the command using the --queue-report-only.  Any AWS access defined for your account will by default be used to print a list of the queues being used by StudioML and their current requirements, if known.

....
queue-status
usage:  queue-status [arguments]      SQS Queue Status tool

Arguments:

  -aws-access-key-id string
        credentials for accessing SQS queues
  -aws-queue string
        A regular expression for selecting the queues to be queries (default "^sqs_.*$")
  -aws-region string
        The region in which this command will query for queues
  -aws-secret-access-key string
        credentials for accessing SQS queues
  -debug
        leave debugging artifacts in place, print internal execution information
  -dry-run
        output the new kubernetes resources on stdout without taking any actions
  -eks-cluster-name string
        cluster name for EKS scaling support, when used the cluster will be scaled out using Jobs
  -in-cluster
        used to indicate if this component is running inside a cluster
  -job-template string
        file containing a Kubernetes Job YAML template sent to the cluster to add runners
  -kubeconfig string
        filepath for the Kubernetes configuration file (default "/home/kmutch/.kube/config")
  -max-cost string
        The maximum permitted cost for all machines, in USD (default "10.00")
  -namespace string
        the namespace being used by jobs being tracked against queues (default "default")
  -queue-report-only
        list queue details only then exit

Environment Variables:

options can be read for environment variables by changing dashes '-' to underscores
and using upper case letters.

To control log levels the LOGXI env variables can be used, these are documented at https://github.com/mgutz/logxi
All logging output goes to stderr, stdout contains command output only.
....

Example output
....
$ ./queue-status --queue-report-only
{
    "sqs_StudioML_kmutch": {
        "Ready": 1,
        "NotVisible": 0,
        "Running": 0,
        "Resource": {
            "cpus": 4,
            "gpus": 1,
            "hdd": "10gb",
            "ram": "2gb",
            "gpuMem": "8G"
        },
        "AWSInstances": [
            {
                "region": "us-west-2",
                "type": "p2.xlarge",
                "price": 0.9
            },
            {
                "region": "us-west-2",
                "type": "p3.2xlarge",
                "price": 3.06
            },
            {
                "region": "us-west-2",
                "type": "p2.8xlarge",
                "price": 7.2
            }
        ]
    },
    "sqs_asd_zues3": {
        "Ready": 0,
        "NotVisible": 0,
        "Running": 0
    }
}
....

=== Template

The tool supports the generation of output that accepts a template file containing Go Template, https://pkg.go.dev/text/template?utm_source=godoc.  The templating is extended to support additional functionality using the Masterminds Sprig library, https://pkg.go.dev/github.com/Masterminds/sprig/v3.

When using a template the standard 100+ sprig functions are available and variables are supplied that are derived from the job characteristics obtained from the queue.  Combining these items with the template will result in a set of Kubernetes resources customized for the queue.

Variables from the queue statistics can be incorporated into the template, for example in the above report sample the Resource ram, as '{{ .Resource.ram }}', or other items in the report can be substituted.  To check the generated variables names available use the --queue-report-only option to see what is available.  Other variables that are available include:

* QueueName The SQS queue name.  Would generally be referenced in the ConfigMap.
* NodeGroup The EKS node group that this work should have affinity to.  Generally referred to within the Job spec.
* Ready The count of StudioML tasks that are waiting on runners.
* NotVisible The count of StudioML tasks that are being worked on by runners
* Running The number of StudioML go runners that are actively running


